In [ ]:
from google.colab import ai
response = ai.generate_text("What is the capital of France?")

In [ ]:
import numpy as np


In [ ]:
brigadas = np.array([[["A","B", "C"], ["D", "E", "F"]],
                     [["G", "H", "C"], ["K", "L", "M"]],
                     [["K", "C", "N"], ["E", "O", "J"]],
                     [["A", "D", "G"], ["C", "E", "M"]],
                     [["N", "L", "I"], ["C", "O", "J"]]])

In [ ]:
brigadas.ndim
brigadas

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['G', 'H', 'C'],
        ['K', 'L', 'M']],

       [['K', 'C', 'N'],
        ['E', 'O', 'J']],

       [['A', 'D', 'G'],
        ['C', 'E', 'M']],

       [['N', 'L', 'I'],
        ['C', 'O', 'J']]], dtype='<U1')

In [ ]:
brigadas[1:3,:,:]

array([[['G', 'H', 'C'],
        ['K', 'L', 'M']],

       [['K', 'C', 'N'],
        ['E', 'O', 'J']]], dtype='<U1')

In [ ]:
brigadas[1:3,:,:].shape

(2, 2, 3)

In [ ]:
brigadas[1:3,1,:]

array([['K', 'L', 'M'],
       ['E', 'O', 'J']], dtype='<U1')

In [ ]:
brigadas[1:3,1,:].shape

(2, 3)

In [ ]:
brigadas[:,1,0:2]

array([['D', 'E'],
       ['K', 'L'],
       ['E', 'O'],
       ['C', 'E'],
       ['C', 'O']], dtype='<U1')

In [ ]:
brigadas[:,1,0:2].shape

(5, 2)

In [ ]:
type(brigadas[4,0,1])

numpy.str_

In [ ]:
sustitutos = np.array([["V","S","W"],
                       ["Z","R","T"]])

In [ ]:
sustitutos.shape

(2, 3)

In [ ]:
brigadas.shape

(5, 2, 3)

In [ ]:
brigadas[4,:,:] = sustitutos

In [ ]:
brigadas

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['G', 'H', 'C'],
        ['K', 'L', 'M']],

       [['K', 'C', 'N'],
        ['E', 'O', 'J']],

       [['A', 'D', 'G'],
        ['C', 'E', 'M']],

       [['V', 'S', 'W'],
        ['Z', 'R', 'T']]], dtype='<U1')

In [ ]:
brigadas[1,1,:] = ["p", "p", "p"]
brigadas

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['G', 'H', 'C'],
        ['p', 'p', 'p']],

       [['K', 'C', 'N'],
        ['E', 'O', 'J']],

       [['A', 'D', 'G'],
        ['C', 'E', 'M']],

       [['V', 'S', 'W'],
        ['Z', 'R', 'T']]], dtype='<U1')

In [ ]:
brigadas[2,0,0:2] = ["y","y"]
brigadas

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['G', 'H', 'C'],
        ['p', 'p', 'p']],

       [['y', 'y', 'N'],
        ['E', 'O', 'J']],

       [['A', 'D', 'G'],
        ['C', 'E', 'M']],

       [['V', 'S', 'W'],
        ['Z', 'R', 'T']]], dtype='<U1')

In [ ]:
brigadas[4,1,2] = "L"
brigadas

array([[['A', 'B', 'C'],
        ['D', 'E', 'F']],

       [['G', 'H', 'C'],
        ['p', 'p', 'p']],

       [['y', 'y', 'N'],
        ['E', 'O', 'J']],

       [['A', 'D', 'G'],
        ['C', 'E', 'M']],

       [['V', 'S', 'W'],
        ['Z', 'R', 'L']]], dtype='<U1')

ARITMETICA Y OPERADORES CON ARREGLOS

Los arreglos de numpy son compatibles con los diversos operadores aritmeticos y logicos de python

In [ ]:
matriz_1 = np.array([[1,2,3],
                    [4,0,-5],
                    [-6,-7,-8]])
matriz_1

array([[ 1,  2,  3],
       [ 4,  0, -5],
       [-6, -7, -8]])

Todas las operaciones siguientes seran aplicadas a todos y cada uno de los elementos del arreglo

In [ ]:
matriz_1 + 100

array([[101, 102, 103],
       [104, 100,  95],
       [ 94,  93,  92]])

In [ ]:
matriz_1[2,:]*3

array([-18, -21, -24])

In [ ]:
3/matriz_1

/tmp/ipykernel_13768/2653568178.py:1: RuntimeWarning: divide by zero encountered in divide
  3/matriz_1


array([[ 3.        ,  1.5       ,  1.        ],
       [ 0.75      ,         inf, -0.6       ],
       [-0.5       , -0.42857143, -0.375     ]])

In [ ]:
matriz_1/2

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  0. , -2.5],
       [-3. , -3.5, -4. ]])

In [ ]:
matriz_1 < 1

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [ ]:
matriz_1.shape

(3, 3)

In [ ]:
matriz_2 = np.array([1,2,3])

In [ ]:
matriz_2.shape

(3,)

In [ ]:
matriz_1 * matriz_2

array([[  1,   4,   9],
       [  4,   0, -15],
       [ -6, -14, -24]])

In [ ]:
matriz_3 = np.array([[2], [4], [6]])

In [ ]:
matriz_3

array([[2],
       [4],
       [6]])

In [ ]:
matriz_3.shape

(3, 1)

In [ ]:
matriz_3 * matriz_1

array([[  2,   4,   6],
       [ 16,   0, -20],
       [-36, -42, -48]])

In [ ]:
import numpy as np
arreglo_2 = np.array([[1,2,3,4],
                     [5,6,7,8],
                     [9, 10,11,12]])

In [ ]:
arreglo_2.shape

(3, 4)

In [ ]:
arreglo_2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
arreglo_2.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
arreglo_2.reshape(12,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arreglo_3 = np.array([[1,2],
                      [3,4]])

In [ ]:
arreglo_3.shape

(2, 2)

In [ ]:
arreglo_3.resize(3,3,2)
arreglo_3

array([[[1, 2],
        [3, 4],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [ ]:
origen = np.arange(9).reshape(3,3,1)
origen

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [ ]:
np.squeeze(origen,2)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arreglo_1 = np.array([[1,2],
                      [3,4]])
arreglo_1

array([[1, 2],
       [3, 4]])

In [ ]:
arreglo__2 =np.array([[5,6],
                      [7,8]])
arreglo__2

array([[5, 6],
       [7, 8]])

In [ ]:
np.concatenate((arreglo_1,arreglo__2), 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.concatenate((arreglo_1,arreglo__2),0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arreglo_original = np.arange(9).reshape(3,3)
arreglo_original

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arreglo_eje_0 = np.array([[5,6,7], [8,9,10]])
arreglo_eje_0

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
np.append(arreglo_original, arreglo_eje_0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  5,  6,  7,  8,  9, 10])

In [ ]:
arreglo_eje_1 = np.arange(7,13).reshape(3,2)
arreglo_eje_1

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
np.append(arreglo_original, arreglo_eje_1, axis=1)

array([[ 0,  1,  2,  7,  8],
       [ 3,  4,  5,  9, 10],
       [ 6,  7,  8, 11, 12]])