In [4]:
import time
lista = list(range(10000000))
inicio = time.time()
[valor * 2 for valor in lista]
print("Tiempo de ejecución con listas: ", time.time()-inicio)

Tiempo de ejecución con listas:  0.7403163909912109


In [3]:
import numpy as np
arreglo = np.array(1000000)
inicio = time.time()

print("Tiempo de ejecución con listas: ", time.time()-inicio)

Tiempo de ejecución con listas:  4.792213439941406e-05


In [5]:
import numpy as np
arreglo = np.arange(1000000)
inicio = time.time()
arreglo * 2
print("Tiempo de ejecución con listas: ", time.time()-inicio)

Tiempo de ejecución con listas:  0.0043070316314697266


In [6]:
!pip install numpy

In [12]:
import numpy as np
arreglo = np.array([1,2,3,4], dtype=int)
print(arreglo)


[1 2 3 4]


In [14]:
print("El numero de dimensiones del arreglo: ", arreglo.ndim)
print("La forma del arreglo es: ", arreglo.shape)
print("El total de elementos del arreglo es: ", arreglo.size)
print("Los tipos de datos en el arreglo son: ", arreglo.dtype)

El numero de dimensiones del arreglo:  1
La forma del arreglo es:  (4,)
El total de elementos del arreglo es:  4
Los tipos de datos en el arreglo son:  int64


In [15]:
arreglo_2d = np.array([[1,2,3],[4,5,6]], dtype=float)
print(arreglo_2d)


[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
print("El numero de dimensiones del arreglo: ", arreglo_2d.ndim)
print("La forma del arreglo es: ", arreglo_2d.shape)
print("El total de elementos del arreglo es: ", arreglo_2d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_2d.dtype)

El numero de dimensiones del arreglo:  2
La forma del arreglo es:  (2, 3)
El total de elementos del arreglo es:  6
Los tipos de datos en el arreglo son:  float64


In [18]:
arreglo_3d = np.array([
    [[1,2,3], [4,5,6]],
    [[7,8,9],[10,11,12]]
])
arreglo_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [19]:
print("El numero de dimensiones del arreglo: ", arreglo_3d.ndim)
print("La forma del arreglo es: ", arreglo_3d.shape)
print("El total de elementos del arreglo es: ", arreglo_3d.size)
print("Los tipos de datos en el arreglo son: ", arreglo_3d.dtype)

El numero de dimensiones del arreglo:  3
La forma del arreglo es:  (2, 2, 3)
El total de elementos del arreglo es:  12
Los tipos de datos en el arreglo son:  int64


In [20]:
ceros = np.zeros((2,3))
ceros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
vacio = np.empty((3,4))
vacio

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
np.random.rand(2,3)

array([[0.8221573 , 0.00196658, 0.38797836],
       [0.5955769 , 0.68239699, 0.21745102]])

In [26]:
arreglo1 = np.array([[1,0],[-1,1]])
print(arreglo1)

[[ 1  0]
 [-1  1]]


In [27]:
arreglo1 / 0

/tmp/ipykernel_8759/1539411815.py:1: RuntimeWarning: divide by zero encountered in divide
  arreglo1 / 0
/tmp/ipykernel_8759/1539411815.py:1: RuntimeWarning: invalid value encountered in divide
  arreglo1 / 0


array([[ inf,  nan],
       [-inf,  inf]])

In [28]:
arreglo2 = np.array([[np.inf,np.nan],[1,2]])
arreglo2

array([[inf, nan],
       [ 1.,  2.]])

In [29]:
array_inf = np.array([1,2.5])**5
print(array_inf)

[ 1.      97.65625]
